batch_size: 16
embed_dim: 8
epochs: 1
losses:
  ChDL1:
    type: ChamferDistanceL1
  ChDL2:
    type: ChamferDistanceL2
optimizer:
  kwargs:
    lr: 0.0001
    weight_decay: 0.0005
  type: AdamW
override_cache: true
pointr_config: PCN_models
run_counter: '1'
run_name: train
save_path: saves/training/
