### PoinTr
pointr_config: PCN_models

### GAPoinTr
resume: false

### Dataset
train_dataset: 'mvp/datasets/MVP_Train_CP.h5'
test_dataset: 'mvp/datasets/MVP_Test_CP.h5'
val_dataset: ''


### Training parameters
batch_size: 16
embed_dim: 8 # 3D clifford algebra
epochs: 1
optimizer : {
  type: AdamW,
  kwargs: {
  lr : 0.005, 
  weight_decay : 0.0005
}}

### Saving parameters
debug: false
override_cache: false
run_name: cdl1_sparse_dense
save_path: saves/training/
