### PoinTr
pointr_config: PCN_models
pretrained: true
load_optimizer: false

### GAPoinTr
version: ''
load_ckp: true
gafte: false

### Dataset
train_dataset: 'mvp/datasets/MVP_Train_CP.h5'
test_dataset: 'mvp/datasets/MVP_Test_CP.h5'


### Training parameters
batch_size: 32
epochs: 1
resume: false
optimizer : {
  type: AdamW,
  kwargs: {
  lr : 0.00005, 
  weight_decay : 0.0005
}}
test_batch: 32

### Run parameters
run_name: pointr-ft-cdc-cdf-mvd
train: true
test: true
debug: false
overwrite_run: true
progressive_saves: true
save_step: 10000
save_path: saves/
dump_dir: debug/
