### PoinTr
pointr_config: PCN_models
pretrained: true
load_optimizer: false

### GAPoinTr
version: ''
load_ckp: true
ckp_file: /PoinTr/saves/PCN_models/experiments/gapointr-cdc-cdf-fold_0/training/19500/checkpoint.pt
gafet: fold


### Dataset
train_dataset: 'mvp/datasets/MVP_Train_CP.h5'
test_dataset: 'mvp/datasets/MVP_Test_CP.h5'

### Training parameters
batch_size: 16
accumulation_step : 4
epochs: 1
resume: false
optimizer: {
  type: AdamW,
  kwargs: {
  lr : 0.00005, 
  weight_decay : 0.00005
}}
test_batch: 32

### Run parameters
run_name: gapointr-cdf-pga
train: true
test: true
debug: false
resume: false
overwrite_run: false
progressive_saves: false
save_step: 1000
save_path: saves/
dump_dir: debug/

### Demo parameters
ft_version: pointr-cdc-cdf_0
step: "final"
version_number: 