### PoinTr
pointr_config: PCN_models

### Dataset


### Training parameters
batch_size: 16
embed_dim: 8 # 3D clifford algebra
epochs: 1
optimizer : {
  type: AdamW,
  kwargs: {
  lr : 0.0005, 
  weight_decay : 0.0005
}}

### Saving parameters
debug: false
override_cache: false
run_name: cdl1_sparse_dense
save_path: saves/training/
